server:
  port: 8082

spring:
  application:
    name: apiCore-sipLog
 
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_SERVER_URL}
          
  datasource:
    url: jdbc:postgresql://postgres-local:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # Muito útil para ver as queries rodando no console durante o desenvolvimento

logging:
  level:
    root: INFO  # Nível padrão para todos os frameworks e bibliotecas
    'br.mackenzie.labEngenhariaSW.sipLog.apiCore_sipLog': DEBUG # Ativa o debug especificamente para o seu código
    org.springframework.web: DEBUG # Mostra informações detalhadas de requisições HTTP
    org.hibernate.SQL: DEBUG # Útil para ver as queries do banco de dados sendo executadas
