version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: sip_postgres
    environment:
      POSTGRES_DB: sip_db
      POSTGRES_USER: sip_user
      POSTGRES_PASSWORD: sip_password
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./volume/postgres:/var/lib/postgresql/data

  # Opcional por agora, mas bom já deixar no esquema para o cache do Feed
  redis:
    image: redis:7-alpine
    container_name: sip_redis
    ports:
      - "6379:6379"