spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_SERVER_URL}

server:
  port: 8081

api:
  core:
    # Se a variável API_CORE_BASE_URL existir no sistema, ele usa ela.
    # Se não existir ele usa o localhost.
    base-url: ${CORE_API_URL:http://localhost:8082}

logging:
  level:
    root: INFO  # Nível padrão para todos os frameworks e bibliotecas
    'br.mackenzie.labEngenhariaSW.sipLogBFF': DEBUG # Ativa o debug especificamente para o seu código
    org.springframework.web: DEBUG # Mostra informações detalhadas de requisições HTTP
    org.hibernate.SQL: DEBUG # Útil para ver as queries do banco de dados sendo executadas
    org.springdoc: DEBUG # Para ver detalhes das operações do SpringDoc OpenAPI
