pipeline {
    agent any

    tools {
        maven 'Maven3' 
        jdk 'JDK21'    
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Mendes1801/sipLog.git' 
            }
        }

        stage('Build (Compilação)') {
            steps {
                echo "--- Compilando a Core API ---"
                dir('core_api/apiCore-sipLog') {
                    sh 'mvn clean compile -DskipTests'
                }

                echo "--- Compilando o BFF ---"
                dir('sipLog-BFF') {
                    sh 'mvn clean compile -DskipTests'
                }
            }
        }

        stage('Test (Testes Unitários)') {
            steps {
                echo "--- Testando a Core API ---"
                dir('core_api/apiCore-sipLog') {
                    sh 'mvn test'
                }

                echo "--- Testando o BFF ---"
                dir('sipLog-BFF') {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    // O asterisco (**) fará o Jenkins procurar relatórios de teste dentro de ambas as pastas
                    junit allowEmptyResults: true,
                          testResults: '**/target/surefire-reports/*.xml'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube-Server') {
                    // Analisando a API (vai criar um projeto no Sonar)
                    dir('core_api/apiCore-sipLog') {
                        sh 'MAVEN_OPTS="--add-opens java.base/java.lang=ALL-UNNAMED" mvn sonar:sonar -Dsonar.projectKey=sipLog-core -Dsonar.projectName="SipLog Core API"'
                    }
                    // Analisando o BFF (vai criar OUTRO projeto no Sonar)
                    dir('sipLog-BFF') {
                        sh 'MAVEN_OPTS="--add-opens java.base/java.lang=ALL-UNNAMED" mvn sonar:sonar -Dsonar.projectKey=sipLog-bff -Dsonar.projectName="SipLog BFF"'
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Package (Gerar Arquivos .jar)') {
            steps {
                echo "--- Empacotando a Core API ---"
                dir('core_api/apiCore-sipLog') {
                    sh 'mvn package -DskipTests'
                }

                echo "--- Empacotando o BFF ---"
                dir('sipLog-BFF') {
                    sh 'mvn package -DskipTests'
                }
            }
        }

        stage('Deploy to App Server') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'sipLog-server-ssh', keyFileVariable: 'SSH_KEY')]) {
                    sh """
                        ssh -i \$SSH_KEY -o StrictHostKeyChecking=no ubuntu@172.31.23.135 '
                            cd /home/ubuntu/sipLog/infra/prodRun
                            
                            # Verifica se o container do banco de dados já existe
                            # docker ps -a -q verifica todos os containers (rodando ou parados) pelo nome
                            DB_EXISTS=\$(sudo docker ps -a -q -f name=sip_postgres_local)
        
                            if [ -z "\$DB_EXISTS" ]; then
                                echo "Ambiente não encontrado. Iniciando provisionamento completo..."
                                
                                # 1. Cria a rede se não existir
                                docker network inspect sip-network >/dev/null 2>&1 || docker network create sip-network
                                
                                # 2. Sobe Spring
                                sudo docker compose --env-file .env.prod -f docker-compose-prod.yml up -d --build
                            else
                                echo "Infraestrutura básica detectada. Realizando deploy incremental..."
                                
                                # Apenas atualiza os serviços Spring, mantendo bancos e Keycloak intactos
                                sudo docker compose --env-file .env.prod -f docker-compose-spring.yml up -d --build
                            fi
                        '
                    """
                    
                    // Copia os .jar para os alvos (mantenha como estava)
                    sh """
                        scp -i \$SSH_KEY -o StrictHostKeyChecking=no core_api/apiCore-sipLog/target/*.jar ubuntu@172.31.23.135:/home/ubuntu/sipLog/core_api/apiCore-sipLog/target/
                        scp -i \$SSH_KEY -o StrictHostKeyChecking=no sipLog-BFF/target/*.jar ubuntu@172.31.23.135:/home/ubuntu/sipLog/sipLog-BFF/target/
                    """
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline executado com sucesso para a Core API e BFF!'
        }
        failure {
            echo 'Pipeline falhou. Verifique os logs.'
        }
        always {
            cleanWs() 
        }
    }
}